version: "3.9"

services:
  mongodb:
    image: 'mongo:6.0'
    container_name: 'ns-us-mongodb'
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./mongo-volume:/data/db

  user_service:
    restart: always
    image: temirovazat/notes-system.user_service:latest
    container_name: ns-user_service
    ports:
      - 10005:10005